language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
before_script:
  - python setup.py develop
script: nosetests
